name: Pull Request Greeting

on:
  pull_request:
    types: [closed]

jobs:
  greet:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check if pull request was merged
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const authorLogin = context.payload.pull_request.user.login;
            const greetingMessage = `🎉 Congratulations, @${authorLogin}! Your pull request was successfully merged. Thank you for your contribution! 🚀`;

            // Add a comment to the pull request with the greeting message
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: greetingMessage
            });
